import { createClient } from 'npm:@supabase/supabase-js@2';
import { PDFDocument, StandardFonts } from 'npm:pdf-lib@1.17.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // ─────────────────────────────────────────────
    // Supabase client (SERVICE ROLE)
    // ─────────────────────────────────────────────
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SERVICE_ROLE_KEY')!
    );

    // ─────────────────────────────────────────────
    // Auth
    // ─────────────────────────────────────────────
    const auth = req.headers.get('authorization');
    if (!auth) throw new Error('Unauthorized');

    const { data: { user } } = await supabase.auth.getUser(
      auth.replace('Bearer ', '')
    );
    if (!user) throw new Error('Unauthorized');

    // ─────────────────────────────────────────────
    // Input
    // ─────────────────────────────────────────────
    const { evidence_id } = await req.json();
    if (!evidence_id) throw new Error('evidence_id is required');

    // ─────────────────────────────────────────────
    // Fetch forensic data
    // ─────────────────────────────────────────────
    const { data: evidence } = await supabase
      .from('evidence')
      .select('*')
      .eq('id', evidence_id)
      .single();

    const { data: hashes } = await supabase
      .from('evidence_hashes')
      .select('*')
      .eq('evidence_id', evidence_id);

    const { data: verifications } = await supabase
      .from('verification_logs')
      .select('*')
      .eq('evidence_id', evidence_id);

    if (!evidence) throw new Error('Evidence not found');

    // ─────────────────────────────────────────────
    // PDF GENERATION
    // ─────────────────────────────────────────────
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595, 842]); // A4
    const font = await pdf.embedFont(StandardFonts.Helvetica);

    let y = 800;
    const lineHeight = 16;

    const draw = (text: string) => {
      page.drawText(text, {
        x: 50,
        y,
        size: 11,
        font,
      });
      y -= lineHeight;
    };

    // ─── Header ────────────────────────────────
    draw('DIGITAL FORENSICS EVIDENCE REPORT');
    y -= 10;
    draw(`Generated at: ${new Date().toISOString()}`);
    draw(`Generated by: ${user.email}`);
    y -= 20;

    // ─── Evidence ──────────────────────────────
    draw('EVIDENCE DETAILS');
    y -= 10;
    draw(`Platform: ${evidence.platform}`);
    draw(`Type: ${evidence.evidence_type}`);
    draw(`Case ID: ${evidence.case_id}`);
    draw(`URL: ${evidence.url}`);
    draw(`Status: ${evidence.status}`);
    y -= 20;

    // ─── Hashes ────────────────────────────────
    draw('CRYPTOGRAPHIC HASHES');
    y -= 10;
    for (const h of hashes || []) {
      draw(`${h.hash_type.toUpperCase()} (${h.hash_algorithm}):`);
      draw(h.hash_value);
      y -= 5;
    }
    y -= 15;

    // ─── Verification Logs ─────────────────────
    draw('VERIFICATION HISTORY');
    y -= 10;
    if (!verifications || verifications.length === 0) {
      draw('No verification attempts recorded.');
    } else {
      for (const v of verifications) {
        draw(`• ${v.created_at} → ${v.is_valid ? 'VALID' : 'TAMPERED'}`);
      }
    }

    // ─────────────────────────────────────────────
    // Final PDF bytes
    // ─────────────────────────────────────────────
    const pdfBytes = await pdf.save();

    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="evidence-report-${evidence_id}.pdf"`,
      },
    });
  } catch (err: any) {
    return new Response(
      JSON.stringify({
        error: err instanceof Error ? err.message : 'Unknown error',
      }),
      {
        status: 400,
        headers: corsHeaders,
      }
    );
  }
});
